@startuml tests

start
note
    update eines Pull Request
    oder push auf main
end note

:Java Setup - Default Version ist nicht 17;
:Durchführen der Tests;
:Veröffentlichen der Ergebnisse;

if (Tests erfolgreich) then (ja)
    stop
    note left #43aa5a : success
else (nein)
    end
    note right #C82333 : fail
endif

@enduml
