name: update
on:
  push:
    branches:
      - main
jobs:
  update-util:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update
          repo: weichware10/util
          token: ${{ secrets.WEICHWARE_UPDATE }}
          inputs: '{ "message": "${{ github.event.commits[0].message }}" }'
  update-toolbox:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update
          repo: weichware10/toolbox
          token: ${{ secrets.WEICHWARE_UPDATE }}
          inputs: '{ "message": "${{ github.event.commits[0].message }}" }'
  update-analyse:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update
          repo: weichware10/analyse
          token: ${{ secrets.WEICHWARE_UPDATE }}
          inputs: '{ "message": "${{ github.event.commits[0].message }}" }'
