name: update
on:
  push:
    branches:
      - main
jobs:
  dispatch-updatev2:
    runs-on: ubuntu-latest
    steps:
      - name: disptach update
        run: |
          curl -XPOST -u "joshuajeschek:${{secrets.WEICHWARE_UPDATE}}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" https://api.github.com/repos/weichware-10/util/actions/workflows/main.yaml/dispatches \
            --data '{"ref": "main"}'
  dispatch-update:
    runs-on: ubuntu-latest
    needs: dispatch-updatev2
    steps:
      - name: dispatch update
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              'weichware-10',
              'util',
              'workflows/update.yaml',
              'main',
              inputs: {
                message: ${{ github.event.head_commit.message }},
              },
            });
          debug: true
