name: update
on:
  push:
    branches:
      - main
jobs:
  dispatch-update:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch update
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              'weichware-10',
              'util',
              'workflows/update.yaml',
              'main',
              inputs: {
                message: ${{ github.event.head_commit.message }},
              },
            });
          debug: true
